name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
    - name: Run Pipeline
      run: |
        ./nextflow run main.nf -profile standard
